### ISSUE TITLE
Bug in Use ThreadPool

### ISSUE THREAD

**Issue by rewufu** [alphamu/ThreadPoolWithCameraPreview#1]
`05-05 14:22:01.185 12725-12734/au.com.alphamu.camerapreviewcaptureimage E/System: Uncaught exception thrown by finalizer
05-05 14:22:01.190 12725-12734/au.com.alphamu.camerapreviewcaptureimage E/System: java.lang.NullPointerException
                                                                                      at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:662)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1362)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.finalize(ThreadPoolExecutor.java:1443)
                                                                                      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
                                                                                      at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
                                                                                      at java.lang.Thread.run(Thread.java:841)`

**Comment by rewufu** [comment]
UncaughtException: RuntimeException:Method called after release()
